fix regression by guarding against URI::Generic.query being nil
URI::Generic.query defaults to nil if there is no query part in the parsed
string, so make sure we don't call methods on nil.

This fixes the already existing request_token tests of which 3/5 are
failing with:
> NoMethodError: undefined method `blank?' for nil:NilClass