fixes NoMethodError when downcasing a symbol
```shell
# Original exception
usr/lib64/ruby/gems/1.8/gems/oauth-0.4.7/lib/oauth/cli.rb:110:in `execute': undefined method `downcase' for :post:Symbol (NoMethodError)
	from /usr/lib64/ruby/gems/1.8/gems/oauth-0.4.7/lib/oauth/cli.rb:19:in `execute'
	from /usr/lib64/ruby/gems/1.8/gems/oauth-0.4.7/bin/oauth:5
	from /usr/bin/oauth:23:in `load'
	from /usr/bin/oauth:23
```

make sure the `options[:method]` is converted to a string before using downcase